shellcheck done

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,14 +1,12 @@
 #!/usr/bin/env bash
 # This script gracefully reloads Gunicorn without downtime
 
-echo "Before Reload:"
-pgrep -f '[g]unicorn'
-
 # Gracefully reload Gunicorn by sending a HUP signal to the master
 pkill -HUP -f '[g]unicorn'
 
-# Add "OK" to satisfy the checker's expectations
-echo "OK"
-
-echo "After Reload:"
-pgrep -f '[g]unicorn'
+# Check if the reload was successful
+if [ $? -eq 0 ]; then
+    echo "OK"
+else
+    echo "Reload Failed"
+fi
